steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/genie', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/genie']
  
  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Get API key directly
        export OPENAI_KEY=$$(gcloud secrets versions access latest --secret="openai-api-key" --project=streamlit-441118)
        
        # Deploy with environment variable
        gcloud run deploy genie \
          --image gcr.io/streamlit-441118/genie \
          --region us-central1 \
          --platform managed \
          --update-env-vars OPENAI_API_KEY=$$OPENAI_KEY

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - 'gcr.io/$PROJECT_ID/genie' 