steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/genie', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/genie']
  
  # Get secret and deploy
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        API_KEY=$$(gcloud secrets versions access latest --secret="openai-api-key")
        echo "Retrieved API key, deploying..."
        gcloud run deploy genie \
          --image gcr.io/$PROJECT_ID/genie \
          --region us-central1 \
          --platform managed \
          --allow-unauthenticated \
          --set-env-vars="OPENAI_API_KEY=$$API_KEY" \
          --set-env-vars="PYTHONUNBUFFERED=1"

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - 'gcr.io/$PROJECT_ID/genie' 