steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/genie', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/genie']
  
  # Get secret
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "$$SECRET" > /workspace/secret.txt
        export OPENAI_API_KEY=$$(cat /workspace/secret.txt)
        gcloud run deploy genie \
          --image gcr.io/$PROJECT_ID/genie \
          --region us-central1 \
          --platform managed \
          --allow-unauthenticated \
          --set-env-vars OPENAI_API_KEY=$$OPENAI_API_KEY
    secretEnv: ['SECRET']

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/openai-api-key/versions/latest
      env: 'SECRET'

images:
  - 'gcr.io/$PROJECT_ID/genie' 