steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/genie', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/genie']
  
  # Get secret and deploy
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        API_KEY=$$(gcloud secrets versions access latest --secret="openai-api-key" --project=$$PROJECT_ID)
        gcloud run deploy genie \
          --image gcr.io/$$PROJECT_ID/genie \
          --region us-central1 \
          --platform managed \
          --allow-unauthenticated \
          --set-env-vars OPENAI_API_KEY="$$API_KEY"
        
        # Add IAM policy binding for public access
        gcloud run services add-iam-policy-binding genie \
          --region=us-central1 \
          --member=allUsers \
          --role=roles/run.invoker

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - 'gcr.io/$PROJECT_ID/genie' 